Repository 3ralon/decide-single-zambrano, pull requests merged in 2023-11, with the labels that each got.

#17 Feat: Implementación de gráficas para la visualización de resultados.
  decide/visualizer/templates/visualizer/visualizer.html
Labels: enhancement

#21 Feat: Implementación de tests de la práctica 2.
  .github/workflows/django.yml
  decide/authentication/test_selenium.py
  decide/authentication/tests.py
  decide/visualizer/tests.py
  decide/voting/tests.py
Labels: enhancement

#22 Fix: Implementación de badges
  README.md
Labels: enhancement

#28 Hotfix/google oauth
  decide/decide/settings.py
  requirements.txt
Labels: bug

#26 Feat/log in log out
  .github/workflows/django.yml
  README.md
  decide/authentication/forms.py
  decide/authentication/serializers.py
  decide/authentication/templates/log_in.html
  decide/authentication/test_selenium.py
  decide/authentication/tests.py
  decide/authentication/urls.py
  decide/authentication/views.py
  decide/decide/urls.py
  decide/mixnet/tests.py
  decide/visualizer/tests.py
  decide/voting/tests.py
Labels: enhancement

#30 Feat/votacion ranking
  decide/booth/templates/booth/booth.html
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/migrations/0006_alter_question_question_type.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: enhancement

#34 Fix: Arreglo del Release workflow
  .github/workflows/django.yml
  .github/workflows/release.yml
  decide/authentication/test_selenium.py
  decide/voting/tests.py
Labels: bug

#45 Test/log in log out
  .github/workflows/release.yml
  decide/authentication/tests.py
  decide/authentication/views.py
Labels: bug, Test

#43 Fix/census
  decide/census/templates/export_csv.html
  decide/census/urls.py
  decide/census/views.py
Labels: enhancement

#41 Feat/plantilas issues
  .github/workflows/issuesTemplates/bug.yml
  .github/workflows/issuesTemplates/feat.yml
  .github/workflows/issuesTemplates/test.yml
  .github/workflows/issuesTemplates/test_test.yml
  .github/workflows/release.yml
  decide/authentication/templates/log_in.html
Labels: documentation, enhancement

#44 Test/visualizer selenium
  .github/workflows/release.yml
  decide/visualizer/test_selenium.py
Labels: Test

#46 fix: configuración entorno personal y github actions
  .gitignore
  decide/authentication/test_selenium.py
  decide/decide/.env.github
  decide/decide/settings.py
Labels: bug

#55 fix: Arreglados los tests de Visualizer
  decide/visualizer/test_selenium.py
Labels: bug

#57 fix: soluciona fallos en tests de voting
  decide/voting/tests.py
Labels: bug, Test

#58 fix: soluciona correcta ordenación del ranking
  decide/voting/models.py
Labels: bug

#60 fix: soluciona comparación entre tally y postproc #56
  decide/voting/tests.py
Labels: bug, Test

#63 fix: selección número de opción para ranking #59
  decide/voting/models.py
Labels: bug

#65 fix: comparación tally y postproc #56
  decide/voting/tests.py
Labels: bug, Test

#66 fix: eliminación test de error
  decide/voting/tests.py
Labels: bug, Test
