Repository 3ralon/decide-single-zambrano, pull requests merged in 2023-12, with the labels that each got.

#68 Feat/Manejo de votaciones
  decide/base/templates/base.html
  decide/booth/templates/booth/home.html
  decide/voting/forms.py
  decide/voting/templates/question_creation.html
  decide/voting/templates/question_list.html
  decide/voting/templates/voting_creation.html
  decide/voting/templates/voting_list.html
  decide/voting/urls.py
  decide/voting/views.py
Labels: enhancement

#54 Fix: Docker #52
  docker/Dockerfile
  docker/docker-compose.yml
  docker/docker-settings.py
Labels: enhancement

#74 Refactor: Limpieza del código de Census Exportation
  decide/census/templates/export_csv.html
  decide/census/views.py
Labels: enhancement

#64 fix: Arreglar la redireccion del formulario de register y testear #61
  decide/authentication/templates/log_in.html
  decide/authentication/templates/registration_form.html
  decide/authentication/test_selenium.py
  decide/authentication/tests.py
  decide/authentication/views.py
  decide/decide/.env.github
Labels: enhancement

#79 Test: Selenium test census #79
  decide/census/templates/export_csv.html
  decide/census/test_selenium.py
Labels: enhancement, Test

#77 Test/census tests
  decide/census/tests.py
  decide/census/views.py
Labels: Test

#82 fix: Arreglo en los test de selenium del censo para que vayan en develop
  decide/census/test_selenium.py
Labels: bug

#80 Hotfix/ Permisos votaciones, eliminar y censo
  decide/base/templates/base.html
  decide/booth/templates/booth/booth.html
  decide/booth/views.py
  decide/visualizer/urls.py
  decide/voting/forms.py
  decide/voting/templates/census_voting.html
  decide/voting/templates/question_list.html
  decide/voting/templates/voting_creation.html
  decide/voting/templates/voting_list.html
  decide/voting/urls.py
  decide/voting/views.py
Labels: bug, enhancement

#94 Test/selenium authentication
  decide/authentication/templates/registration_form.html
  decide/authentication/test_selenium.py
  decide/authentication/tests.py
  decide/authentication/views.py
Labels: Test

#96 Feat/configurar linter
  .pre-commit-config.yaml
  requirements.txt
Labels: documentation, enhancement

#98 Feat: Integrar Census en Homepage #97
  decide/authentication/test_selenium.py
  decide/base/templates/base.html
Labels: enhancement

#105 fix: Corrección del redireccionamiento tras registrar un usuario
  decide/authentication/templates/log_in.html
  decide/authentication/tests.py
  decide/authentication/views.py
Labels: bug

#110 Test: casos límite voting con selenium
  decide/voting/tests.py
Labels: Test

#111 Fix/render
  .github/ISSUE_TEMPLATE/bugs-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/test-template.md
  .github/workflows/launch.sh
  decide/decide/settings.py
  decide/local_settings.deploy.py
  launch.sh
Labels: bug

#113 Test/homepage voting tests
  decide/voting/templates/403.html
  decide/voting/tests.py
  decide/voting/views.py
Labels: Test

#116 Test: checkear census antes de votar
  decide/booth/tests.py
  decide/voting/tests.py
Labels: Test

#117 Fix/census check before voting
  decide/booth/views.py
Labels: bug

#121 fix: modifica headless a true en voting #120
  decide/voting/tests.py
Labels: bug

#122 Fix/actualizar readme
  README.md
Labels: documentation

#119 Volcado de develop a master
  README.md
  decide/booth/tests.py
  decide/booth/views.py
  decide/voting/templates/403.html
  decide/voting/tests.py
  decide/voting/views.py
Labels: enhancement

#124 Fix/django.yml
  .github/workflows/deploy.yml
  .github/workflows/django.yml
Labels: bug

#125 Fix:Django.yml
  .github/workflows/deploy.yml
  .github/workflows/django.yml
Labels: bug

#132 Fix: Duplicado de Censo
  decide/voting/views.py
Labels: bug

#129 fix: login en docker #126
  docker/docker-compose.yml
Labels: bug

#133 Volcado a develop con nuevos parches
  decide/voting/views.py
  docker/docker-compose.yml
Labels: bug

#137 Feat/regular user exportar
  decide/census/views.py
Labels: bug
